# Generated by Django 4.0.6 on 2022-10-29 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class_dnd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Person_state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('XP', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('description', models.CharField(max_length=200)),
                ('hit_dice', models.IntegerField(default=0)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CharList.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Save_throws',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.CharField(max_length=200)),
                ('dexterity', models.CharField(max_length=200)),
                ('constitution', models.CharField(max_length=200)),
                ('intelligence', models.CharField(max_length=200)),
                ('wisdom', models.CharField(max_length=200)),
                ('charisma', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acrobatics', models.CharField(max_length=200)),
                ('animal_handling', models.CharField(max_length=200)),
                ('arcana', models.CharField(max_length=200)),
                ('athletics', models.CharField(max_length=200)),
                ('deception', models.CharField(max_length=200)),
                ('history', models.CharField(max_length=200)),
                ('insight', models.CharField(max_length=200)),
                ('intimidation', models.CharField(max_length=200)),
                ('investigation', models.CharField(max_length=200)),
                ('medicine', models.CharField(max_length=200)),
                ('nature', models.CharField(max_length=200)),
                ('perception', models.CharField(max_length=200)),
                ('performance', models.CharField(max_length=200)),
                ('persuasion', models.CharField(max_length=200)),
                ('religion', models.CharField(max_length=200)),
                ('sleight_of_hand', models.CharField(max_length=200)),
                ('stealth', models.CharField(max_length=200)),
                ('survival', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Spell_set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Person_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CharList.person_state')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CharList.spell')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CharList.master')),
            ],
        ),
        migrations.AddField(
            model_name='person_state',
            name='save_throws',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CharList.save_throws'),
        ),
        migrations.AddField(
            model_name='person_state',
            name='skills',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CharList.skills'),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('person_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CharList.person_state')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CharList.race')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CharList.user')),
            ],
        ),
        migrations.CreateModel(
            name='Item_set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CharList.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CharList.session'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='item_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CharList.item_set'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CharList.person_state')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CharList.session')),
            ],
        ),
        migrations.CreateModel(
            name='Classes_dnd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_dnd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CharList.class_dnd')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CharList.person')),
            ],
        ),
    ]
