# Generated by Django 4.1.3 on 2022-11-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharList', '0012_remove_inventory_item_set_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='save_throws',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
