# Generated by Django 4.1.3 on 2022-11-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharList', '0015_remove_person_classes_dnd_classes_dnd_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes_dnd',
            name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='classes_dnd',
            field=models.ManyToManyField(null=True, to='CharList.classes_dnd'),
        ),
    ]
