# Generated by Django 4.1.3 on 2022-11-19 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CharList', '0018_remove_person_class_dnd_person_main_class_dnd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person_state',
            name='description',
        ),
    ]
