# Generated by Django 4.1.3 on 2022-11-13 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CharList', '0008_alter_person_user_alter_session_master_delete_master_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='person_state',
        ),
        migrations.AddField(
            model_name='person_state',
            name='person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CharList.person'),
        ),
    ]
