# Generated by Django 4.1.3 on 2022-11-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharList', '0016_remove_classes_dnd_person_person_classes_dnd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='classes_dnd',
        ),
        migrations.AddField(
            model_name='person',
            name='class_dnd',
            field=models.ManyToManyField(null=True, to='CharList.class_dnd'),
        ),
        migrations.DeleteModel(
            name='Classes_dnd',
        ),
    ]
