# Generated by Django 4.1.3 on 2022-11-16 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CharList', '0017_remove_person_classes_dnd_person_class_dnd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='class_dnd',
        ),
        migrations.AddField(
            model_name='person',
            name='main_class_dnd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CharList.class_dnd'),
        ),
        migrations.AddField(
            model_name='person_state',
            name='classes_dnd',
            field=models.ManyToManyField(blank=True, to='CharList.class_dnd'),
        ),
    ]
